name: flutter_minesweeper
description: Minesweeper for Flutter web.
version: 1.0.0+1
author: Shayne Kelly II
repository: https://github.com/shaynekellyii/flutter_minesweeper

environment:
  sdk: ">=2.3.0 <3.0.0"

# Trying to keep the amount of 3rd-party dependencies as small as possible.
dependencies:
  flutter:
    sdk: flutter
  pedantic: ^1.8.0
  provider: ^3.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Latest version of test that's still compatible with flutter_test
  test: ^1.5.0

flutter:
  uses-material-design: true

  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  fonts:
    - family: Dosis
      fonts:
        - asset: fonts/Dosis-Regular.ttf
        - asset: fonts/Dosis-Bold.ttf
          weight: 700
